name: CICD
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: create .env file from secrets
        run: |
          echo "BOT_TOKEN=$BOT_TOKEN" >> .env
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      - run: cat .env
      - run: npm i
      - run: npm start
