name: CICD
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: create .env file from secrets
        run: |
          echo "BOT_TOKEN=$BOT_TOKEN" >> .env
          echo "SSH_PASSWORD=$SSH_PASSWORD" >> .env
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      - run: cat .env
      - name: Check for running processes
        run: |
          pm2 list
          if [ $? -eq 0 ]; then
            pm2 stop all
            pm2 delete all
          else
            echo "No processes running, nothing to stop or delete."
          fi
      - run: npm i
      - run: npm start
