name: CICD
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: create .env file from secrets
        run: |
          echo "MY_ENV_VAR=$MY_ENV_VAR" >> .env
          echo "ANOTHER_ENV_VAR=$ANOTHER_ENV_VAR" >> .env
        env:
          MY_ENV_VAR: ${{ secrets.TOKEN }}
      - run: npm i
      - run: npm start
